// ============================================================
// KEEPSTEAD™ — THEME CONFIG
// Source of truth for all colors across all themes.
// Pull from this file. Never hardcode colors anywhere else.
// ============================================================

export const THEMES = {
  daylight: {
    id: "daylight",
    label: "Daylight",
    navBg: "#FFFFFF",
    navBorder: "#E5EAF0",
    logoPrimary: "#1A2A3A",
    logoAccent: "#2563EB",
    heroBg: "#F7FAFF",
    eyebrow: "#2563EB",
    h1Color: "#1A2A3A",
    h1Accent: "#2563EB",
    subColor: "#4A5568",
    btnBg: "#2563EB",
    btnText: "#FFFFFF",
    roomBg: "#EEF4FF",
    roomNameColor: "#1A2A3A",
    roomDescColor: "#4A5568",
    priceBorder: "#E5EAF0",
    priceBg: "#EEF4FF",
    priceAmt: "#1A2A3A",
    priceLbl: "#4A5568",
    inputBg: "#FFFFFF",
    inputBorder: "#CBD5E0",
    inputText: "#1A2A3A",
    cardBg: "#FFFFFF",
    cardBorder: "#E5EAF0",
  },

  garden: {
    id: "garden",
    label: "Garden",
    navBg: "#F6F2FF",
    navBorder: "#D4C8F0",
    logoPrimary: "#1F1040",
    logoAccent: "#6B3FA0",
    heroBg: "#EEF7EE",
    eyebrow: "#2D7A3A",
    h1Color: "#1F1040",
    h1Accent: "#6B3FA0",
    subColor: "#3D5A3E",
    btnBg: "#6B3FA0",
    btnText: "#F6F2FF",
    roomBg: "#E8F5E8",
    roomNameColor: "#1F1040",
    roomDescColor: "#3D5A3E",
    priceBorder: "#D4C8F0",
    priceBg: "#F0E8FF",
    priceAmt: "#1F1040",
    priceLbl: "#3D5A3E",
    inputBg: "#FFFFFF",
    inputBorder: "#D4C8F0",
    inputText: "#1F1040",
    cardBg: "#FFFFFF",
    cardBorder: "#D4C8F0",
  },

  hearth: {
    id: "hearth",
    label: "Hearth",
    navBg: "#FDF9F3",
    navBorder: "#E8E0D4",
    logoPrimary: "#1E1A14",
    logoAccent: "#C1603A",
    heroBg: "#FAF6EF",
    eyebrow: "#C1603A",
    h1Color: "#1E1A14",
    h1Accent: "#C1603A",
    subColor: "#5A5348",
    btnBg: "#C1603A",
    btnText: "#FDF9F3",
    roomBg: "#F0EBE3",
    roomNameColor: "#1E1A14",
    roomDescColor: "#7A6F65",
    priceBorder: "#E8E0D4",
    priceBg: "#F0EBE3",
    priceAmt: "#1E1A14",
    priceLbl: "#7A6F65",
    inputBg: "#FFFFFF",
    inputBorder: "#E8E0D4",
    inputText: "#1E1A14",
    cardBg: "#FFFFFF",
    cardBorder: "#E8E0D4",
  },

  slate: {
    id: "slate",
    label: "Slate",
    navBg: "#1A1F2E",
    navBorder: "#2D3448",
    logoPrimary: "#E8EAF0",
    logoAccent: "#7C9EF8",
    heroBg: "#141824",
    eyebrow: "#7C9EF8",
    h1Color: "#F0F2F8",
    h1Accent: "#7C9EF8",
    subColor: "#8B93A8",
    btnBg: "#7C9EF8",
    btnText: "#141824",
    roomBg: "#1E2436",
    roomNameColor: "#E8EAF0",
    roomDescColor: "#8B93A8",
    priceBorder: "#2D3448",
    priceBg: "#1E2436",
    priceAmt: "#F0F2F8",
    priceLbl: "#8B93A8",
    inputBg: "#1E2436",
    inputBorder: "#2D3448",
    inputText: "#E8EAF0",
    cardBg: "#1E2436",
    cardBorder: "#2D3448",
  },

  sunflower: {
    id: "sunflower",
    label: "Sunflower",
    navBg: "#FFFDF0",
    navBorder: "#F0E0A0",
    logoPrimary: "#2C2200",
    logoAccent: "#D4A017",
    heroBg: "#FFFBEA",
    eyebrow: "#B8860B",
    h1Color: "#2C2200",
    h1Accent: "#D4A017",
    subColor: "#5C4A00",
    btnBg: "#D4A017",
    btnText: "#FFFDF0",
    roomBg: "#FFF5C8",
    roomNameColor: "#2C2200",
    roomDescColor: "#7A6000",
    priceBorder: "#F0E0A0",
    priceBg: "#FFF5C8",
    priceAmt: "#2C2200",
    priceLbl: "#7A6000",
    inputBg: "#FFFFFF",
    inputBorder: "#F0E0A0",
    inputText: "#2C2200",
    cardBg: "#FFFFF0",
    cardBorder: "#F0E0A0",
  },

  walnut: {
    id: "walnut",
    label: "Walnut",
    navBg: "#2C1F14",
    navBorder: "#4A3020",
    logoPrimary: "#F5EDE0",
    logoAccent: "#C8956A",
    heroBg: "#231810",
    eyebrow: "#C8956A",
    h1Color: "#F5EDE0",
    h1Accent: "#C8956A",
    subColor: "#B09880",
    btnBg: "#C8956A",
    btnText: "#231810",
    roomBg: "#3A2818",
    roomNameColor: "#F5EDE0",
    roomDescColor: "#B09880",
    priceBorder: "#4A3020",
    priceBg: "#3A2818",
    priceAmt: "#F5EDE0",
    priceLbl: "#B09880",
    inputBg: "#3A2818",
    inputBorder: "#4A3020",
    inputText: "#F5EDE0",
    cardBg: "#3A2818",
    cardBorder: "#4A3020",
  },

  // Stained Glass is handled differently — see STAINED_GLASS_ROOMS below.
  // The theme object here is a neutral fallback only.
  stainedglass: {
    id: "stainedglass",
    label: "Stained Glass",
    // Colors come from the active room — see STAINED_GLASS_ROOMS
    // These are fallback values only (Commons colors)
    navBg: "#DBEAFE",
    navBorder: "#BFDBFE",
    logoPrimary: "#1A2A3A",
    logoAccent: "#2563EB",
    heroBg: "#EEF4FF",
    eyebrow: "#2563EB",
    h1Color: "#1A2A3A",
    h1Accent: "#2563EB",
    subColor: "#4A5568",
    btnBg: "#2563EB",
    btnText: "#FFFFFF",
    roomBg: "#EEF4FF",
    roomNameColor: "#1A2A3A",
    roomDescColor: "#4A5568",
    priceBorder: "#BFDBFE",
    priceBg: "#DBEAFE",
    priceAmt: "#1A2A3A",
    priceLbl: "#4A5568",
    inputBg: "#FFFFFF",
    inputBorder: "#BFDBFE",
    inputText: "#1A2A3A",
    cardBg: "#FFFFFF",
    cardBorder: "#BFDBFE",
  },
};

// ============================================================
// STAINED GLASS — room-aware palettes
// When theme = stainedglass, the active room drives all colors.
// ============================================================

export const STAINED_GLASS_ROOMS = {
  commons: {
    accent: "#2563EB",
    bg: "#EEF4FF",
    navBg: "#DBEAFE",
    text: "#1A2A3A",
    sub: "#4A5568",
    btnBg: "#2563EB",
    btnText: "#FFFFFF",
    priceBg: "#DBEAFE",
    priceBorder: "#BFDBFE",
  },
  provision: {
    accent: "#D4A017",
    bg: "#FFF9E6",
    navBg: "#FFF3CC",
    text: "#2C2200",
    sub: "#7A6000",
    btnBg: "#D4A017",
    btnText: "#2C2200",
    priceBg: "#FFF3CC",
    priceBorder: "#F0E0A0",
  },
  ledger: {
    accent: "#059669",
    bg: "#ECFDF5",
    navBg: "#D1FAE5",
    text: "#064E3B",
    sub: "#065F46",
    btnBg: "#059669",
    btnText: "#FFFFFF",
    priceBg: "#D1FAE5",
    priceBorder: "#A7F3D0",
  },
  stronghold: {
    accent: "#DC2626",
    bg: "#FEF2F2",
    navBg: "#FEE2E2",
    text: "#450A0A",
    sub: "#7F1D1D",
    btnBg: "#DC2626",
    btnText: "#FFFFFF",
    priceBg: "#FEE2E2",
    priceBorder: "#FECACA",
  },
  mending: {
    accent: "#B06080",
    bg: "#FDF2F4",
    navBg: "#F9E0E6",
    text: "#3A1020",
    sub: "#7A4050",
    btnBg: "#B06080",
    btnText: "#FFFFFF",
    priceBg: "#F9E0E6",
    priceBorder: "#F0C0CC",
  },
  legacy: {
    accent: "#7C3AED",
    bg: "#F5F0FF",
    navBg: "#EDE9FE",
    text: "#2E1065",
    sub: "#4C1D95",
    btnBg: "#7C3AED",
    btnText: "#FFFFFF",
    priceBg: "#EDE9FE",
    priceBorder: "#DDD6FE",
  },
  harvest: {
    accent: "#C2410C",
    bg: "#FFF7ED",
    navBg: "#FFEDD5",
    text: "#431407",
    sub: "#7C2D12",
    btnBg: "#C2410C",
    btnText: "#FFFFFF",
    priceBg: "#FFEDD5",
    priceBorder: "#FED7AA",
  },
};

export const THEME_ORDER = [
  "daylight",
  "garden",
  "hearth",
  "slate",
  "stainedglass",
  "sunflower",
  "walnut",
];

export const DEFAULT_THEME = "daylight";
